language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      brew_packages: tmux
      r: release
      env: R_CODECOV=true

r_packages:
  - covr

apt_packages:
  - tmux

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
