language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode8.3
      brew_packages: tmux
      env: R_CODECOV=true

r_packages:
  - covr

r_github_packages:
  - datascienceworkshops/tmuxr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then Rscript -e 'library(covr); codecov()'; fi
