language: r
r: release
cache:
  apt: true
  packages: true
latex: false
pandoc: false

jobs:
- env: TMUX_VERSION=3.1
  r: devel
- env: TMUX_VERSION=3.0a
  r: devel
- env: TMUX_VERSION=3.1
  r: oldrel
- env: TMUX_VERSION=3.0a
  r: oldrel
- env: TMUX_VERSION=3.1b
- env: TMUX_VERSION=3.1a
- env: TMUX_VERSION=3.1
- env: TMUX_VERSION=3.0a
- env: TMUX_VERSION=3.0
- env: TMUX_VERSION=2.9a
- env: TMUX_VERSION=2.9
- env: TMUX_VERSION=2.8
- env: TMUX_VERSION=2.7
- env: TMUX_VERSION=2.6
- env: TMUX_VERSION=2.5
- env: TMUX_VERSION=2.4
- env: TMUX_VERSION=2.3
- env: TMUX_VERSION=2.2
- env: TMUX_VERSION=2.1
- os: osx

addons:
  apt:
    packages:
    - gcc
    - libevent-dev
    - ncurses-dev
  homebrew:
    packages:
    - tmux

r_packages:
- covr

warnings_are_errors: true

before_install: ./bin/install-tmux-travis.sh

notifications:
  email:
    on_success: change
    on_failure: change
